name: deploy myblog

on:
  push:
    branches:
      - 'main' # 针对 main 分支
    paths:
      - '.github/workflows/*'
      - 'src/**'
      - 'bin/*'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # 第三的 action

      - name: create a folder # 创建文件夹
        run: mkdir test-folder
      - name: print id_rsa # 打印我的 id_rsa
        run: |
          echo "start..."
          echo "${{secrets.MY_ID_RSA}}"
          echo "end..."
      - name: create a file # 创建文件
        run: |
          cd test-folder
          touch a.txt
          echo "hello word" > a.txt
          cat a.txt
      - name: delete a file
        run: rm -rf a.txt